checkpoint

diff --git a/forecast/do-forecast b/forecast/do-forecast
--- a/forecast/do-forecast
+++ b/forecast/do-forecast
@@ -30,21 +30,25 @@ fi
 # is too long.
 #
 export UFS_DOMAIN_SELECT_HOME=`echo $(realpath $(dirname $0))/.. | sed 's/\/forecast\/\.\.//'`
-EXPT_BASEDIR=$UFS_DOMAIN_SELECT_HOME/build/expt
-EXPT_SUBDIR=test_${STACK}
+
+EXPT_BASEDIR=$UFS_DOMAIN_SELECT_HOME/build/exp-$STACK-$VER
+EXPT_SUBDIR=test
+
+#EXPT_BASEDIR=$UFS_DOMAIN_SELECT_HOME/build/expt
+#EXPT_SUBDIR=test_${STACK}
 
 echo "### Experiment path is $EXPT_BASEDIR/$EXPT_SUBDIR"
 length=`echo $EXPT_BASEDIR/$EXPT_SUBDIR | wc -c`
-#echo "length is $length"
+echo "length is $length"
 sleep 1
 
-#if [ $length -gt 63 ]; then
-#	echo
-#	echo "Bad experiment directory path: \"$EXPT_BASEDIR/$EXPT_SUBDIR\""
-#	echo "Path length is $length"
-#	echo "Path length cannot exceed 63 bytes"
-#	exit 1
-#fi
+if [ $length -gt 61 ]; then
+	echo
+	echo "Bad experiment directory path: \"$EXPT_BASEDIR/$EXPT_SUBDIR\""
+	echo "Path length is $length"
+	echo "Path length cannot exceed 61 bytes"
+	exit 1
+fi
 
 EXTRN_MDL_SOURCE_BASEDIR_ICS=$UFS_DOMAIN_SELECT_HOME/build/DATA-$VER/input_model_data/FV3GFS/grib2/2019061518
 EXTRN_MDL_SOURCE_BASEDIR_LBCS=$UFS_DOMAIN_SELECT_HOME/build/DATA-$VER/input_model_data/FV3GFS/grib2/2019061518
