checkpoint

diff --git a/forecast/do-forecast b/forecast/do-forecast
--- a/forecast/do-forecast
+++ b/forecast/do-forecast
@@ -24,21 +24,28 @@ fi
 
 #
 # Be careful here. The setting of EXPT_SUBDIR leads to strange
-# errors in run_make_orog.sh, particularly if the subdirectory
-# name is greater than 14 bytes. 
+# errors in run_make_orog.sh, particularly if the path length
+# is too long.
 #
-export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
-EXPT_BASEDIR=${UFS_DOMAIN_SELECT_HOME}/build/expt_dirs
-EXPT_SUBDIR=test_${STACK}_sta
+export UFS_DOMAIN_SELECT_HOME=`echo $(realpath $(dirname $0))/.. | sed 's/\/forecast\/\.\.//'`
+EXPT_BASEDIR=$UFS_DOMAIN_SELECT_HOME/build/expt
+EXPT_SUBDIR=test_${STACK}_stack
 
-if [ `echo $EXPT_SUBDIR | wc -c` -gt 16 ]; then
+echo "Experiment path is $EXPT_BASEDIR/$EXPT_SUBDIR"
+length=`echo $EXPT_BASEDIR/$EXPT_SUBDIR | wc -c`
+#echo "length is $length"
+sleep 1
+
+if [ $length -gt 63 ]; then
 	echo
-	echo "WARNING: EXPT_SUBDIR ($EXPT_SUBDIR) is too long"
-	echo "WARNING: This may lead to errors in run_make_orog."
-	echo "WARNING: It's best to keep it less than 14 bytes."
-	echo
-	sleep 3
+	echo "Bad experiment directory path: \"$EXPT_BASEDIR/$EXPT_SUBDIR\""
+	echo "Path length is $length"
+	echo "Path length cannot exceed 63 bytes"
+	exit 1
 fi
+
+EXTRN_MDL_SOURCE_BASEDIR_ICS=/home/mmesnie/ufs_domain_select/build/DATA-2.2.0/input_model_data/FV3GFS/grib2/2019061518
+EXTRN_MDL_SOURCE_BASEDIR_LBCS=/home/mmesnie/ufs_domain_select/build/DATA-2.2.0/input_model_data/FV3GFS/grib2/2019061518
 
 export EXPTDIR=$EXPT_BASEDIR/$EXPT_SUBDIR
 
@@ -48,7 +55,7 @@ export EXPTDIR=$EXPT_BASEDIR/$EXPT_SUBDIR
 
 cd ${UFS_DOMAIN_SELECT_HOME}/forecast || exit 1
 
-cat config.yaml.tmpl | sed "s|<EXPT_SUBDIR>|${EXPT_SUBDIR}|g" > ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush/config.yaml || exit 1 
+cat config.yaml.tmpl | sed "s|<EXPT_SUBDIR>|${EXPT_SUBDIR}|g" | sed "s|<EXPT_BASEDIR>|${EXPT_BASEDIR}|g" | sed "s|<EXTRN_MDL_SOURCE_BASEDIR_ICS>|${EXTRN_MDL_SOURCE_BASEDIR_ICS}|g" | sed "s|<EXTRN_MDL_SOURCE_BASEDIR_LBCS>|${EXTRN_MDL_SOURCE_BASEDIR_LBCS}|g" > ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush/config.yaml || exit 1 
 
 cat linux-$VER.yaml.tmpl | sed "s|<UFS_DOMAIN_SELECT_HOME>|${UFS_DOMAIN_SELECT_HOME}|g" > ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush/machine/linux.yaml || exit 1
 
@@ -83,8 +90,7 @@ export PYTHONPATH="$PYTHONPATH:$UFS_DOMAIN_SELECT_HOME/build/ufs-srweather-app-2
 cd ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush || exit 1
 ./generate_FV3LAM_wflow.py || exit 1
 
-mkdir -p ${EXPTDIR} || exit 1
-cd ${EXPTDIR} || exit 1
+cd $EXPTDIR || exit 1
 cp ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush/wrappers/* . || exit 1
 
 ./run_make_grid.sh || exit 1
