checkpoint

diff --git a/forecast/do-forecast b/forecast/do-forecast
--- a/forecast/do-forecast
+++ b/forecast/do-forecast
@@ -38,13 +38,13 @@ length=`echo $EXPT_BASEDIR/$EXPT_SUBDIR | wc -c`
 #echo "length is $length"
 sleep 1
 
-if [ $length -gt 63 ]; then
-	echo
-	echo "Bad experiment directory path: \"$EXPT_BASEDIR/$EXPT_SUBDIR\""
-	echo "Path length is $length"
-	echo "Path length cannot exceed 63 bytes"
-	exit 1
-fi
+#if [ $length -gt 63 ]; then
+#	echo
+#	echo "Bad experiment directory path: \"$EXPT_BASEDIR/$EXPT_SUBDIR\""
+#	echo "Path length is $length"
+#	echo "Path length cannot exceed 63 bytes"
+#	exit 1
+#fi
 
 EXTRN_MDL_SOURCE_BASEDIR_ICS=$UFS_DOMAIN_SELECT_HOME/build/DATA-$VER/input_model_data/FV3GFS/grib2/2019061518
 EXTRN_MDL_SOURCE_BASEDIR_LBCS=$UFS_DOMAIN_SELECT_HOME/build/DATA-$VER/input_model_data/FV3GFS/grib2/2019061518
