checkpoint

diff --git a/forecast/do-forecast b/forecast/do-forecast
--- a/forecast/do-forecast
+++ b/forecast/do-forecast
@@ -22,10 +22,25 @@ else
         exit 1
 fi
 
+#
+# Be careful here. The setting of EXPT_SUBDIR leads to strange
+# errors in run_make_orog.sh, particularly if the subdirectory
+# name is greater than 14 bytes. 
+#
 export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
-export EXPT_BASEDIR=${UFS_DOMAIN_SELECT_HOME}/build/expt_dirs
-EXPT_SUBDIR=test_$STACK
-export EXPTDIR=${EXPT_BASEDIR}/${EXPT_SUBDIR}
+EXPT_BASEDIR=${UFS_DOMAIN_SELECT_HOME}/build/expt_dirs
+EXPT_SUBDIR=test_${STACK}_sta
+
+if [ `echo $EXPT_SUBDIR | wc -c` -gt 16 ]; then
+	echo
+	echo "WARNING: EXPT_SUBDIR ($EXPT_SUBDIR) is too long"
+	echo "WARNING: This may lead to errors in run_make_orog."
+	echo "WARNING: It's best to keep it less than 14 bytes."
+	echo
+	sleep 3
+fi
+
+export EXPTDIR=$EXPT_BASEDIR/$EXPT_SUBDIR
 
 #
 # Apply patches to UFS
@@ -68,6 +83,7 @@ export PYTHONPATH="$PYTHONPATH:$UFS_DOMAIN_SELECT_HOME/build/ufs-srweather-app-2
 cd ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush || exit 1
 ./generate_FV3LAM_wflow.py || exit 1
 
+mkdir -p ${EXPTDIR} || exit 1
 cd ${EXPTDIR} || exit 1
 cp ${UFS_DOMAIN_SELECT_HOME}/build/ufs-srweather-app-$VER-with-$STACK-stack/ush/wrappers/* . || exit 1
 
diff --git a/forecast/do-plot b/forecast/do-plot
--- a/forecast/do-plot
+++ b/forecast/do-plot
@@ -1,14 +1,24 @@
 #!/bin/bash
 
-if [ $# != 1 ]; then
-        echo "usage: $0 <2.2.0|3.0.0>"
+if [ $# != 2 ]; then
+        echo "usage: $0 <hpc|spack|zee> <2.2.0|3.0.0>"
         exit 1
 fi
 
-if [ "$1" == "2.2.0" ]; then
-        VER=$1
+if [ ! $1 == "hpc" ] && [ ! $1 == "spack" ] && [ ! $1 == "zee" ]; then
+        echo \"$1\" is an invalid stack
+        echo "usage: $0 <hpc|spack|zee> <2.2.0|3.0.0>"
+        exit 1
+fi
+
+if [ "$2" == "2.2.0" ]; then
+        STACK=$1
+        VER=$2
+elif [ "$2" == "3.0.0" ]; then
+        echo "$1 not yet implemented"
+        exit 1
 else
-        echo "$1 not supported"
+        echo "$2 not supported"
         exit 1
 fi
 
@@ -18,7 +28,7 @@ eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"
 
 conda activate regional_workflow-$VER || exit 1
 
-cd ${UFS_DOMAIN_SELECT_HOME}/build/expt_dirs/ufs_domain_select_OR_coast/*/postprd/
+cd ${UFS_DOMAIN_SELECT_HOME}/build/expt_dirs/test_$STACK/*/postprd/
 
 rm -f *.png
 
