checkpoint

diff --git a/forecast/do-post b/forecast/do-post
--- a/forecast/do-post
+++ b/forecast/do-post
@@ -1,20 +1,43 @@
 #!/bin/bash
 
-if [ $# != 1 ]; then
-        echo "usage: $0 <2.1.0|2.2.0>"
+if [ $# != 2 ]; then
+        echo "usage: $0 <hpc|spack|spack-lmod> <2.2.0|3.0.0>"
         exit 1
 fi
 
-if [ "$1" == "2.2.0" ]; then
-        VER=$1
+if [ ! $1 == "hpc" ] && [ ! $1 == "spack" ] && [ ! $1 == "spack-lmod" ]; then
+        echo \"$1\" is an invalid stack
+        echo "usage: $0 <hpc|spack|spack-lmod> <2.2.0|3.0.0>"
+        exit 1
+fi
+
+if [ "$2" == "2.2.0" ]; then
+        STACK=$1
+        VER=$2
+elif [ "$2" == "3.0.0" ]; then
+        echo "$1 not yet implemented"
+        exit 1
 else
-        echo "$1 not supported"
+        echo "$2 not supported"
         exit 1
 fi
 
 export UFS_DOMAIN_SELECT_HOME=$(realpath $(dirname $0))/..
 export EXPT_BASEDIR=${UFS_DOMAIN_SELECT_HOME}/build/expt_dirs
 export EXPTDIR=${EXPT_BASEDIR}/ufs_domain_select_OR_coast
+
+if [ $STACK == "spack" ] || [ $STACK == "spack-lmod" ]; then
+        source $UFS_DOMAIN_SELECT_HOME/build/$STACK-stack-for-$VER/share/spack/setup-env.sh || exit 1
+        if [ $STACK == "spack" ]; then
+                echo "### $0: activating ufs spack environment"
+                spack env activate ufs -p || exit 1
+        else
+                echo "### $0: activating ufs-lmod spack environment"
+                spack env activate ufs-lmod -p || exit 1
+        fi
+        export LD_LIBRARY_PATH="`spack location -i jasper`/lib:$LD_LIBRARY_PATH"
+        export LD_LIBRARY_PATH="`spack location -i netcdf-fortran`/lib:$LD_LIBRARY_PATH"
+fi
 
 eval "$(${UFS_DOMAIN_SELECT_HOME}/build/anaconda3/bin/conda shell.bash hook)"
 conda activate regional_workflow-$VER || exit 1
