checkpoint

diff --git a/stack/build-hpc-stack b/stack/build-hpc-stack
--- a/stack/build-hpc-stack
+++ b/stack/build-hpc-stack
@@ -52,3 +52,11 @@ export PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/gnu-11/openmpi/4.1.2/b
 export LD_LIBRARY_PATH="${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER/gnu-11/openmpi/4.1.2/lib:"$LD_LIBRARY_PATH
 
 ./build_stack.sh -p ${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER -c ./config/config_custom.sh -y stack/stack_custom.yaml -m
+
+num=`find ${UFS_DOMAIN_SELECT_HOME}/build/opt-for-$VER -name "*.lua" | wc -l`
+
+if [ $num != 61 ]; then
+	echo "$num modules installed (expected 61)"
+	echo "hpc stack failed to build -- try running script again"
+	exit 1
+fi
